### PR TITLE
Example for "--folding-style travis" feature

### PR DESCRIPTION
**Pull request by skalee**
Write usage example for the folding feature, and test it.

### CODE REVIEW

**Comment by ronaldtse** [comment]
LGTM but I'll let @dewyatt give his take.

**Comment by skalee** [comment]
Yes, I know. It's because of some typo in implementation. I wanted to see full test results in Travis first.

**Comment by skalee** [comment]
BTW bug is now fixed (with the 2nd commit).

**Comment by ronaldtse** [comment]
Thanks guys!

**Pull request merged**
