### PR TITLE
Write some usage examples, and test popular use cases in Travis CI

### PR DESCRIPTION
**Pull request by skalee**
Every example is tested in Travis CI.  They all together comprise a test suite for `gpg-build-scripts`.  Every example is arranged as follows: it begins with a variable definitions block, which is followed with actual installation commands, and ends with a sequence of assertions which confirm installation correctness.  Every example includes comments.

### CODE REVIEW

**Comment by skalee** [comment]
@dewyatt You may want to take a look at these. Maybe you have something to add, or to improve?

**Comment by dewyatt** [comment]
@skalee Thanks but there are a few issues I see:
1. The usage of `install_gpg_all.sh` appears bogus since it's supposed to be of the syntax `./install_gpg_all.sh -i 2.2`, rather than `./install_gpg_all.sh 2.2`. It is silently changed to "latest" in all usages in these tests. But if you actually use it correctly, you'll get an error since `GPG_VERSION` is a readonly and is later reassigned.
2. A few of the tests only pass because the regex is flawed. With `grep -e "\b2\.1"` it will happily match characters 3-5 of `2.2.10`. Maybe try `grep -e "\s2\.1\."` instead.
3. I'd really like to see better arg validation. (most of the other issues are related)
4. `./install_gpg_all.sh head` is probably supposed to be `master` (`git checkout head` isn't going to work).
5. `set -x` would be good when `$CI` is `"true"`.
6. There's a lot of duplication.

**Comment by ronaldtse** [comment]
Thanks @skalee @dewyatt . I agree with the latest comments that the code can be improved. @skalee could you help fix them to merge? Thanks!

**Comment by skalee** [comment]
Thanks for precious input! I knew it's worth to ask you for opinion.

> @skalee Thanks but there are a few issues I see:
> 
> 1. The usage of `install_gpg_all.sh` appears bogus since it's supposed to be of the syntax `./install_gpg_all.sh -i 2.2`, rather than `./install_gpg_all.sh 2.2`. It is silently changed to "latest" in all usages in these tests. But if you actually use it correctly, you'll get an error since `GPG_VERSION` is a readonly and is later reassigned.

😮 Indeed, you're right. Apparently, synopsis has changed since I wrote it, and I didn't notice that at all… Well, I never stumbled upon any issue because of this thing, because neither of my gems (AFAIR) is tested against GnuPG 2.1 due to some discrepancies I haven't handled properly yet.

Furthermore, both README and in-script comments are outdated as well.

> 2. A few of the tests only pass because the regex is flawed. With `grep -e "\b2\.1"` it will happily match characters 3-5 of `2.2.10`. Maybe try `grep -e "\s2\.1\."` instead (or something even more strict).
>
> 3. I'd really like to see better arg validation. (most of the other issues are related)
>
> 4. `./install_gpg_all.sh head` is probably supposed to be `master` (but see item 1)

All above are true. Thanks.

> 5. `set -x` would be good when `$CI` is `"true"`.

Ok.

> 6. There's a lot of duplication.

These scripts are meant to serve as documentation in the first place. I considered extracting assertion definitions to some helper script, but I think it would be an unnecessary complication, potentially unreadable for Bash newbies.

**Comment by skalee** [comment]
> 1. The usage of `install_gpg_all.sh` appears bogus since it's supposed to be of the syntax `./install_gpg_all.sh -i 2.2`, rather than `./install_gpg_all.sh 2.2`. It is silently changed to "latest" in all usages in these tests. But if you actually use it correctly, you'll get an error since `GPG_VERSION` is a readonly and is later reassigned.

I'm leaving it broken as of current pull request. This is a separate thing, and deserves its own pull request, preferably done in TDD (so I need these tests first). Extracted to issue #13.

> 2. A few of the tests only pass because the regex is flawed. With `grep -e "\b2\.1"` it will happily match characters 3-5 of `2.2.10`. Maybe try `grep -e "\s2\.1\."` instead (or something even more strict).

Fixed!

> 3. I'd really like to see better arg validation. (most of the other issues are related)

TODO in #15.

> 4. `./install_gpg_all.sh head` is probably supposed to be `master` (but see item 1)

Replaced with "master", but still broken due to #13.

> 5. `set -x` would be good when `$CI` is `"true"`.

After testing it, I think that it somewhat clutters the output, actually. Though I am not strongly against it, I am not going to introduce it unless you or @ronaldtse really want it.

> 6. There's a lot of duplication.

As I answered previously.

----

I would like to merge it. I prefer to have failing (but good) tests rather than no tests, especially when fixing recently created issues #13, #14, and #15. Your opinions are welcome, especially on point 5 and 6.

**Comment by ronaldtse** [comment]
@dewyatt @skalee I suppose the error raised with '2.1' here 
https://travis-ci.org/riboseinc/gpg-build-scripts/jobs/451457256 is a known issue and should not block the merge, right?

**Comment by dewyatt** [comment]
@ronaldtse Yes, I believe he has filed appropriate GH issues and would like to add the tests in this PR first, even if they're failing (and then tackle the issues individually).

**Comment by skalee** [comment]
Yes, it is a simple thing to fix. Error happens because the local variable is marked as read only. Nevertheless, I am thinking about moving some responsibilities to "install component" script in order to make the "install all" as simple as possible. That means that most likely more changes will be made.

**Comment by ronaldtse** [comment]
Thank you guys!

**Pull request merged**
