### PR TITLE
Change programs' interfaces

### PR DESCRIPTION
**Pull request by skalee**
For this option, `--at` is a better name than `--version`, as `--version` conventionally means "print program version and exit".

This is a breaking change.

cc: @ronaldtse, @dewyatt.

### CODE REVIEW

**Comment by skalee** [comment]
See also ##14.

**Comment by dewyatt** [comment]
Not a big deal but what do you think about something more descriptive like `--component-version`? I just think `--at` isn't very intuitive.

**Comment by ronaldtse** [comment]
Agreed.

**Comment by skalee** [comment]
Please treat this pull request asa  work-in-progress for now.

**Comment by dewyatt** [comment]
> The only doubt I have is related to using `--component-version` together with `--git` option. In such case, `--component-version` should be a Git branch or tag. A more ambiguous `--at` was more suitable for that.
> 
> However, maybe we change approach here, and define yet another option `--component-git-ref` which would be used instead of `--component-version` in this case? I think it's a good idea. I'll add some commits to address that.

I don't really see any issues with having `--git --component-version gnupg-2.2.11`, `--git --component-version fe621cc`, `--component-version latest` all be valid uses. 
Adding another git-specific option adds unnecessary complexity IMO, I don't think we need a `--component-git-ref`.

**Comment by skalee** [comment]
I have implemented this change already, and IMO it makes things bit cleaner. I can revert it though if someone doesn't like it.

**Comment by ronaldtse** [comment]
@skalee the build is failing. Does it matter?

**Comment by skalee** [comment]
@ronaldtse It is out of scope of this pull request. Nevertheless, these failures are not false positives. Fixes will be included in further pull requests.

**Comment by skalee** [comment]
In `install_gpg_component.sh` script:

* option `--component` has been renamed to `--component-name`
* option `--version` has been renamed to `--component-version`
* option `--git` has been removed in favour of `--component-git-ref`

In `install_gpg_all.sh` script:

* option `-i` has been renamed to `--suite-version`, and fixed
* other options except for `--help` have been removed
* code style has been improved

Documentation has been updated for both scripts.

Fixes #14.

**Pull request merged**
